echo "Writing to " $2
mkdir -p $2
echo "Extracting club info"
export BASE=`basename $1`
jq -r -f ./src/jq/club-csv.jq $1 > "$2/$BASE-club.csv"
echo "Extracting hole info"
jq -r -f ./src/jq/hole-csv.jq $1 > "$2/$BASE-hole.csv"
echo "Extracting score info"
jq -r -f ./src/jq/scorecard-csv.jq $1 > "$2/$BASE-scorecard.csv"
echo "Extracting shot row info"
jq -r -f ./src/jq/shot-detail-row-order.jq $1 > "$2/$BASE-shots-row.csv"
echo "Extracting shot column info"
jq -r -f ./src/jq/shot-detail-col-order.jq $1 > "$2/$BASE-shots-col.csv"
echo "Extracting Last 10 Stats"
jq -r -f ./src/jq/last-10-stats.jq $1 > "$2/$BASE-last-10-stats.csv"
echo "Extracting Last 10 Drive"
jq -r -f ./src/jq/last-10-drive.jq $1 > "$2/$BASE-last-10-drive.csv"
echo "Extracting Last 10 approach"
jq -r -f ./src/jq/last-10-approach.jq $1 > "$2/$BASE-last-10-approach.csv"
echo "Extracting Last 10 chip"
jq -r -f ./src/jq/last-10-approach.jq $1 > "$2/$BASE-last-10-approach.csv"
echo "Extracting Last 10 putt"
jq -r -f ./src/jq/last-10-putt.jq $1 > "$2/$BASE-last-10-putt.csv"